# coding: utf-8

"""
    Nevaya Platform

    Access to everything Nevaya  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@nevaya.co.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.cast_api import CastApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCastApi(unittest.TestCase):
    """CastApi unit test stubs"""

    def setUp(self):
        self.api = CastApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_cast_chromecasts(self):
        """Test case for get_cast_chromecasts

        Get a list of chromecasts  # noqa: E501
        """
        pass

    def test_get_cast_chromecasts_id(self):
        """Test case for get_cast_chromecasts_id

        Get a chromecast  # noqa: E501
        """
        pass

    def test_get_cast_connections(self):
        """Test case for get_cast_connections

        Get all valid connections  # noqa: E501
        """
        pass

    def test_post_cast_chromecasts(self):
        """Test case for post_cast_chromecasts

        Get a list of chromecasts  # noqa: E501
        """
        pass

    def test_post_cast_chromecasts_id_reboot(self):
        """Test case for post_cast_chromecasts_id_reboot

        Reboot the chromecast(s)  # noqa: E501
        """
        pass

    def test_post_cast_chromecasts_id_reset(self):
        """Test case for post_cast_chromecasts_id_reset

        Reset the chromecast(s)  # noqa: E501
        """
        pass

    def test_post_cast_chromecasts_pairing_codes(self):
        """Test case for post_cast_chromecasts_pairing_codes

        Get the pairing codes for the chromecast(s)  # noqa: E501
        """
        pass

    def test_post_cast_connections(self):
        """Test case for post_cast_connections

        Get all valid connections  # noqa: E501
        """
        pass

    def test_post_cast_connections_connect(self):
        """Test case for post_cast_connections_connect

        Connect a guest device  # noqa: E501
        """
        pass

    def test_post_cast_connections_expire(self):
        """Test case for post_cast_connections_expire

        Expire connections  # noqa: E501
        """
        pass

    def test_put_cast_chromecasts_id(self):
        """Test case for put_cast_chromecasts_id

        Update a chromecast  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
