# coding: utf-8

"""
    Nevaya Platform

    Access to everything Nevaya  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@nevaya.co.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20028_data import InlineResponse20028Data  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20028Data(unittest.TestCase):
    """InlineResponse20028Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20028Data(self):
        """Test InlineResponse20028Data"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20028_data.InlineResponse20028Data()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
