# coding: utf-8

"""
    Nevaya Platform

    Access to everything Nevaya  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@nevaya.co.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.movie_movie_languages import MovieMovieLanguages  # noqa: E501
from swagger_client.rest import ApiException


class TestMovieMovieLanguages(unittest.TestCase):
    """MovieMovieLanguages unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMovieMovieLanguages(self):
        """Test MovieMovieLanguages"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.movie_movie_languages.MovieMovieLanguages()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
