# coding: utf-8

"""
    Nevaya Platform

    Access to everything Nevaya  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@nevaya.co.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.reservations_api import ReservationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestReservationsApi(unittest.TestCase):
    """ReservationsApi unit test stubs"""

    def setUp(self):
        self.api = ReservationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_reservations(self):
        """Test case for delete_reservations

        Delete reservation(s)  # noqa: E501
        """
        pass

    def test_get_account_profiles(self):
        """Test case for get_account_profiles

        Get a list of available account profiles  # noqa: E501
        """
        pass

    def test_get_reservations(self):
        """Test case for get_reservations

        Get reservations  # noqa: E501
        """
        pass

    def test_get_reservations_id(self):
        """Test case for get_reservations_id

        Retrieve a reservation  # noqa: E501
        """
        pass

    def test_post_get_reservations(self):
        """Test case for post_get_reservations

        Get reservations  # noqa: E501
        """
        pass

    def test_post_reservations(self):
        """Test case for post_reservations

        Check a guest into a room  # noqa: E501
        """
        pass

    def test_put_reservations_id(self):
        """Test case for put_reservations_id

        Update a reservation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
