# coding: utf-8

"""
    Nevaya Platform

    Access to everything Nevaya  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@nevaya.co.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cast_connections_body import CastConnectionsBody  # noqa: E501
from swagger_client.rest import ApiException


class TestCastConnectionsBody(unittest.TestCase):
    """CastConnectionsBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCastConnectionsBody(self):
        """Test CastConnectionsBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cast_connections_body.CastConnectionsBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
