# coding: utf-8

"""
    Nevaya Platform

    Access to everything Nevaya  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@nevaya.co.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.room_control_api import RoomControlApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRoomControlApi(unittest.TestCase):
    """RoomControlApi unit test stubs"""

    def setUp(self):
        self.api = RoomControlApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_room_control_info(self):
        """Test case for get_room_control_info

        Room control info  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
