# coding: utf-8

"""
    Nevaya Platform

    Access to everything Nevaya  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@nevaya.co.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.epg_api import EPGApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEPGApi(unittest.TestCase):
    """EPGApi unit test stubs"""

    def setUp(self):
        self.api = EPGApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_epg_now_and_next(self):
        """Test case for get_epg_now_and_next

        Get the programmes that are on now and next  # noqa: E501
        """
        pass

    def test_get_epg_programmes(self):
        """Test case for get_epg_programmes

        Get EPG data  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
