# coding: utf-8

"""
    Nevaya Platform

    Access to everything Nevaya  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@nevaya.co.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.maintenance_api import MaintenanceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMaintenanceApi(unittest.TestCase):
    """MaintenanceApi unit test stubs"""

    def setUp(self):
        self.api = MaintenanceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_maintenance_items(self):
        """Test case for get_maintenance_items

        Get a list of available maintenance items  # noqa: E501
        """
        pass

    def test_get_maintenance_requests(self):
        """Test case for get_maintenance_requests

        Get a list of maintenance requests  # noqa: E501
        """
        pass

    def test_post_maintenance_requests(self):
        """Test case for post_maintenance_requests

        Create a maintenance request  # noqa: E501
        """
        pass

    def test_put_maintenance_requests(self):
        """Test case for put_maintenance_requests

        Update a maintenance request  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
