# coding: utf-8

"""
    Nevaya Platform

    Access to everything Nevaya  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@nevaya.co.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.rooms_api import RoomsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRoomsApi(unittest.TestCase):
    """RoomsApi unit test stubs"""

    def setUp(self):
        self.api = RoomsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_rooms(self):
        """Test case for get_rooms

        Get rooms  # noqa: E501
        """
        pass

    def test_get_rooms_id(self):
        """Test case for get_rooms_id

        Get a room  # noqa: E501
        """
        pass

    def test_post_rooms(self):
        """Test case for post_rooms

        Get rooms  # noqa: E501
        """
        pass

    def test_put_rooms_id(self):
        """Test case for put_rooms_id

        Update a room  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
