# coding: utf-8

"""
    Nevaya Platform

    Access to everything Nevaya  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@nevaya.co.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.room_status import RoomStatus  # noqa: E501
from swagger_client.rest import ApiException


class TestRoomStatus(unittest.TestCase):
    """RoomStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoomStatus(self):
        """Test RoomStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.room_status.RoomStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
