# coding: utf-8

"""
    Nevaya Platform

    Access to everything Nevaya  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@nevaya.co.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.movies_api import MoviesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMoviesApi(unittest.TestCase):
    """MoviesApi unit test stubs"""

    def setUp(self):
        self.api = MoviesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_guests_id_movies(self):
        """Test case for get_guests_id_movies

        Get all the movies purchased  # noqa: E501
        """
        pass

    def test_get_movies(self):
        """Test case for get_movies

        Get the available movies  # noqa: E501
        """
        pass

    def test_post_movies_purchases(self):
        """Test case for post_movies_purchases

        Purchase a movie  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
