# coding: utf-8

"""
    Nevaya Platform

    Access to everything Nevaya  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@nevaya.co.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.touch_api import TouchApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTouchApi(unittest.TestCase):
    """TouchApi unit test stubs"""

    def setUp(self):
        self.api = TouchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_post_touch_token(self):
        """Test case for post_touch_token

        Get a token to use in Touch API  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
