# coding: utf-8

"""
    Nevaya Platform

    Access to everything Nevaya  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@nevaya.co.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.tv_api import TVApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTVApi(unittest.TestCase):
    """TVApi unit test stubs"""

    def setUp(self):
        self.api = TVApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_tv_receivers(self):
        """Test case for get_tv_receivers

        Get receivers  # noqa: E501
        """
        pass

    def test_get_tv_receivers_embeddable_remote(self):
        """Test case for get_tv_receivers_embeddable_remote

        Get a link to an application that can be displayed in an iframe  # noqa: E501
        """
        pass

    def test_get_tv_receivers_id_applications(self):
        """Test case for get_tv_receivers_id_applications

        Get a list of applications available to the receiver  # noqa: E501
        """
        pass

    def test_get_tv_receivers_id_channels(self):
        """Test case for get_tv_receivers_id_channels

        Get all channels available to a receiver  # noqa: E501
        """
        pass

    def test_get_tv_receivers_id_data(self):
        """Test case for get_tv_receivers_id_data

        Get all the data for a receiver  # noqa: E501
        """
        pass

    def test_get_tv_receivers_id_movies(self):
        """Test case for get_tv_receivers_id_movies

        Get all movies available to the receiver  # noqa: E501
        """
        pass

    def test_get_tv_receivers_id_sources(self):
        """Test case for get_tv_receivers_id_sources

        Get external sources for a receiver  # noqa: E501
        """
        pass

    def test_get_tv_receivers_id_videos(self):
        """Test case for get_tv_receivers_id_videos

        Get videos for a receiver  # noqa: E501
        """
        pass

    def test_post_tv_receivers(self):
        """Test case for post_tv_receivers

        Get receivers  # noqa: E501
        """
        pass

    def test_post_tv_receivers_control(self):
        """Test case for post_tv_receivers_control

        Control multiple receivers  # noqa: E501
        """
        pass

    def test_post_tv_receivers_id_applications_close(self):
        """Test case for post_tv_receivers_id_applications_close

        Close the currently open application on the receiver(s)  # noqa: E501
        """
        pass

    def test_post_tv_receivers_id_applications_open(self):
        """Test case for post_tv_receivers_id_applications_open

        Open an application on the receiver(s)  # noqa: E501
        """
        pass

    def test_post_tv_receivers_id_channels_play(self):
        """Test case for post_tv_receivers_id_channels_play

        Change the channel on the receiver(s)  # noqa: E501
        """
        pass

    def test_post_tv_receivers_id_movies_play(self):
        """Test case for post_tv_receivers_id_movies_play

        Play a movie on a receiver  # noqa: E501
        """
        pass

    def test_post_tv_receivers_id_sources_exit(self):
        """Test case for post_tv_receivers_id_sources_exit

        Exit the current external source on the receiver(s)  # noqa: E501
        """
        pass

    def test_post_tv_receivers_id_sources_switch(self):
        """Test case for post_tv_receivers_id_sources_switch

        Switch external source on the receiver(s)  # noqa: E501
        """
        pass

    def test_post_tv_receivers_id_videos_play(self):
        """Test case for post_tv_receivers_id_videos_play

        Play a video on the receiver(s)  # noqa: E501
        """
        pass

    def test_post_tv_receivers_pairing_codes(self):
        """Test case for post_tv_receivers_pairing_codes

        Get the pairing codes for the receiver(s)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
