# coding: utf-8

"""
    Nevaya Platform

    Access to everything Nevaya  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@nevaya.co.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.chromecast import Chromecast  # noqa: F401,E501

class AllOfinlineResponse20019Data(Chromecast):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'room': 'Room'
    }
    if hasattr(Chromecast, "swagger_types"):
        swagger_types.update(Chromecast.swagger_types)

    attribute_map = {
        'room': 'room'
    }
    if hasattr(Chromecast, "attribute_map"):
        attribute_map.update(Chromecast.attribute_map)

    def __init__(self, room=None, *args, **kwargs):  # noqa: E501
        """AllOfinlineResponse20019Data - a model defined in Swagger"""  # noqa: E501
        self._room = None
        self.discriminator = None
        if room is not None:
            self.room = room
        Chromecast.__init__(self, *args, **kwargs)

    @property
    def room(self):
        """Gets the room of this AllOfinlineResponse20019Data.  # noqa: E501


        :return: The room of this AllOfinlineResponse20019Data.  # noqa: E501
        :rtype: Room
        """
        return self._room

    @room.setter
    def room(self, room):
        """Sets the room of this AllOfinlineResponse20019Data.


        :param room: The room of this AllOfinlineResponse20019Data.  # noqa: E501
        :type: Room
        """

        self._room = room

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AllOfinlineResponse20019Data, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AllOfinlineResponse20019Data):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
