# coding: utf-8

"""
    Nevaya Platform

    Access to everything Nevaya  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@nevaya.co.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConnectionsExpireBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'room_id': 'str',
        'chromecast_id': 'str',
        'room_name_eq': 'str',
        'room_name_cont': 'str',
        'guest_device_mac': 'str'
    }

    attribute_map = {
        'room_id': 'room_id',
        'chromecast_id': 'chromecast_id',
        'room_name_eq': 'room_name_eq',
        'room_name_cont': 'room_name_cont',
        'guest_device_mac': 'guest_device_mac'
    }

    def __init__(self, room_id=None, chromecast_id=None, room_name_eq=None, room_name_cont=None, guest_device_mac=None):  # noqa: E501
        """ConnectionsExpireBody - a model defined in Swagger"""  # noqa: E501
        self._room_id = None
        self._chromecast_id = None
        self._room_name_eq = None
        self._room_name_cont = None
        self._guest_device_mac = None
        self.discriminator = None
        if room_id is not None:
            self.room_id = room_id
        if chromecast_id is not None:
            self.chromecast_id = chromecast_id
        if room_name_eq is not None:
            self.room_name_eq = room_name_eq
        if room_name_cont is not None:
            self.room_name_cont = room_name_cont
        if guest_device_mac is not None:
            self.guest_device_mac = guest_device_mac

    @property
    def room_id(self):
        """Gets the room_id of this ConnectionsExpireBody.  # noqa: E501

        The room ID  # noqa: E501

        :return: The room_id of this ConnectionsExpireBody.  # noqa: E501
        :rtype: str
        """
        return self._room_id

    @room_id.setter
    def room_id(self, room_id):
        """Sets the room_id of this ConnectionsExpireBody.

        The room ID  # noqa: E501

        :param room_id: The room_id of this ConnectionsExpireBody.  # noqa: E501
        :type: str
        """

        self._room_id = room_id

    @property
    def chromecast_id(self):
        """Gets the chromecast_id of this ConnectionsExpireBody.  # noqa: E501

        The chromecast ID  # noqa: E501

        :return: The chromecast_id of this ConnectionsExpireBody.  # noqa: E501
        :rtype: str
        """
        return self._chromecast_id

    @chromecast_id.setter
    def chromecast_id(self, chromecast_id):
        """Sets the chromecast_id of this ConnectionsExpireBody.

        The chromecast ID  # noqa: E501

        :param chromecast_id: The chromecast_id of this ConnectionsExpireBody.  # noqa: E501
        :type: str
        """

        self._chromecast_id = chromecast_id

    @property
    def room_name_eq(self):
        """Gets the room_name_eq of this ConnectionsExpireBody.  # noqa: E501

        The room name contains the value  # noqa: E501

        :return: The room_name_eq of this ConnectionsExpireBody.  # noqa: E501
        :rtype: str
        """
        return self._room_name_eq

    @room_name_eq.setter
    def room_name_eq(self, room_name_eq):
        """Sets the room_name_eq of this ConnectionsExpireBody.

        The room name contains the value  # noqa: E501

        :param room_name_eq: The room_name_eq of this ConnectionsExpireBody.  # noqa: E501
        :type: str
        """

        self._room_name_eq = room_name_eq

    @property
    def room_name_cont(self):
        """Gets the room_name_cont of this ConnectionsExpireBody.  # noqa: E501

        The room name matches the value exactly  # noqa: E501

        :return: The room_name_cont of this ConnectionsExpireBody.  # noqa: E501
        :rtype: str
        """
        return self._room_name_cont

    @room_name_cont.setter
    def room_name_cont(self, room_name_cont):
        """Sets the room_name_cont of this ConnectionsExpireBody.

        The room name matches the value exactly  # noqa: E501

        :param room_name_cont: The room_name_cont of this ConnectionsExpireBody.  # noqa: E501
        :type: str
        """

        self._room_name_cont = room_name_cont

    @property
    def guest_device_mac(self):
        """Gets the guest_device_mac of this ConnectionsExpireBody.  # noqa: E501

        The MAC address of the guest device  # noqa: E501

        :return: The guest_device_mac of this ConnectionsExpireBody.  # noqa: E501
        :rtype: str
        """
        return self._guest_device_mac

    @guest_device_mac.setter
    def guest_device_mac(self, guest_device_mac):
        """Sets the guest_device_mac of this ConnectionsExpireBody.

        The MAC address of the guest device  # noqa: E501

        :param guest_device_mac: The guest_device_mac of this ConnectionsExpireBody.  # noqa: E501
        :type: str
        """

        self._guest_device_mac = guest_device_mac

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConnectionsExpireBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConnectionsExpireBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
