# coding: utf-8

"""
    Nevaya Platform

    Access to everything Nevaya  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@nevaya.co.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConnectionsConnectBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'guest_device_id': 'str',
        'guest_device_mac': 'str',
        'chromecast_id': 'str',
        'hours': 'OneOfconnectionsConnectBodyHours'
    }

    attribute_map = {
        'guest_device_id': 'guest_device_id',
        'guest_device_mac': 'guest_device_mac',
        'chromecast_id': 'chromecast_id',
        'hours': 'hours'
    }

    def __init__(self, guest_device_id=None, guest_device_mac=None, chromecast_id=None, hours=None):  # noqa: E501
        """ConnectionsConnectBody - a model defined in Swagger"""  # noqa: E501
        self._guest_device_id = None
        self._guest_device_mac = None
        self._chromecast_id = None
        self._hours = None
        self.discriminator = None
        if guest_device_id is not None:
            self.guest_device_id = guest_device_id
        if guest_device_mac is not None:
            self.guest_device_mac = guest_device_mac
        self.chromecast_id = chromecast_id
        if hours is not None:
            self.hours = hours

    @property
    def guest_device_id(self):
        """Gets the guest_device_id of this ConnectionsConnectBody.  # noqa: E501

        The ID of the guest device  # noqa: E501

        :return: The guest_device_id of this ConnectionsConnectBody.  # noqa: E501
        :rtype: str
        """
        return self._guest_device_id

    @guest_device_id.setter
    def guest_device_id(self, guest_device_id):
        """Sets the guest_device_id of this ConnectionsConnectBody.

        The ID of the guest device  # noqa: E501

        :param guest_device_id: The guest_device_id of this ConnectionsConnectBody.  # noqa: E501
        :type: str
        """

        self._guest_device_id = guest_device_id

    @property
    def guest_device_mac(self):
        """Gets the guest_device_mac of this ConnectionsConnectBody.  # noqa: E501

        The MAC address of the guest device  # noqa: E501

        :return: The guest_device_mac of this ConnectionsConnectBody.  # noqa: E501
        :rtype: str
        """
        return self._guest_device_mac

    @guest_device_mac.setter
    def guest_device_mac(self, guest_device_mac):
        """Sets the guest_device_mac of this ConnectionsConnectBody.

        The MAC address of the guest device  # noqa: E501

        :param guest_device_mac: The guest_device_mac of this ConnectionsConnectBody.  # noqa: E501
        :type: str
        """

        self._guest_device_mac = guest_device_mac

    @property
    def chromecast_id(self):
        """Gets the chromecast_id of this ConnectionsConnectBody.  # noqa: E501

        The chromecast ID  # noqa: E501

        :return: The chromecast_id of this ConnectionsConnectBody.  # noqa: E501
        :rtype: str
        """
        return self._chromecast_id

    @chromecast_id.setter
    def chromecast_id(self, chromecast_id):
        """Sets the chromecast_id of this ConnectionsConnectBody.

        The chromecast ID  # noqa: E501

        :param chromecast_id: The chromecast_id of this ConnectionsConnectBody.  # noqa: E501
        :type: str
        """
        if chromecast_id is None:
            raise ValueError("Invalid value for `chromecast_id`, must not be `None`")  # noqa: E501

        self._chromecast_id = chromecast_id

    @property
    def hours(self):
        """Gets the hours of this ConnectionsConnectBody.  # noqa: E501

        The number of hours to allow the guest device access to the chromecast. Passing `permanent` means that the connection will never automatically expire  # noqa: E501

        :return: The hours of this ConnectionsConnectBody.  # noqa: E501
        :rtype: OneOfconnectionsConnectBodyHours
        """
        return self._hours

    @hours.setter
    def hours(self, hours):
        """Sets the hours of this ConnectionsConnectBody.

        The number of hours to allow the guest device access to the chromecast. Passing `permanent` means that the connection will never automatically expire  # noqa: E501

        :param hours: The hours of this ConnectionsConnectBody.  # noqa: E501
        :type: OneOfconnectionsConnectBodyHours
        """

        self._hours = hours

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConnectionsConnectBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConnectionsConnectBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
