# coding: utf-8

"""
    Nevaya Platform

    Access to everything Nevaya  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@nevaya.co.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20026(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'epg_id': 'str',
        'programmes': 'list[EPGProgramme]'
    }

    attribute_map = {
        'epg_id': 'epg_id',
        'programmes': 'programmes'
    }

    def __init__(self, epg_id=None, programmes=None):  # noqa: E501
        """InlineResponse20026 - a model defined in Swagger"""  # noqa: E501
        self._epg_id = None
        self._programmes = None
        self.discriminator = None
        if epg_id is not None:
            self.epg_id = epg_id
        if programmes is not None:
            self.programmes = programmes

    @property
    def epg_id(self):
        """Gets the epg_id of this InlineResponse20026.  # noqa: E501

        The EPG ID of the channel  # noqa: E501

        :return: The epg_id of this InlineResponse20026.  # noqa: E501
        :rtype: str
        """
        return self._epg_id

    @epg_id.setter
    def epg_id(self, epg_id):
        """Sets the epg_id of this InlineResponse20026.

        The EPG ID of the channel  # noqa: E501

        :param epg_id: The epg_id of this InlineResponse20026.  # noqa: E501
        :type: str
        """

        self._epg_id = epg_id

    @property
    def programmes(self):
        """Gets the programmes of this InlineResponse20026.  # noqa: E501


        :return: The programmes of this InlineResponse20026.  # noqa: E501
        :rtype: list[EPGProgramme]
        """
        return self._programmes

    @programmes.setter
    def programmes(self, programmes):
        """Sets the programmes of this InlineResponse20026.


        :param programmes: The programmes of this InlineResponse20026.  # noqa: E501
        :type: list[EPGProgramme]
        """

        self._programmes = programmes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20026, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20026):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
