# coding: utf-8

"""
    Nevaya Platform

    Access to everything Nevaya  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@nevaya.co.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MoviesPurchasesBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'guest_id': 'str',
        'reservation_id': 'str',
        'room_id': 'str',
        'movie_id': 'str'
    }

    attribute_map = {
        'guest_id': 'guest_id',
        'reservation_id': 'reservation_id',
        'room_id': 'room_id',
        'movie_id': 'movie_id'
    }

    def __init__(self, guest_id=None, reservation_id=None, room_id=None, movie_id=None):  # noqa: E501
        """MoviesPurchasesBody - a model defined in Swagger"""  # noqa: E501
        self._guest_id = None
        self._reservation_id = None
        self._room_id = None
        self._movie_id = None
        self.discriminator = None
        if guest_id is not None:
            self.guest_id = guest_id
        if reservation_id is not None:
            self.reservation_id = reservation_id
        if room_id is not None:
            self.room_id = room_id
        self.movie_id = movie_id

    @property
    def guest_id(self):
        """Gets the guest_id of this MoviesPurchasesBody.  # noqa: E501

        The guest ID  # noqa: E501

        :return: The guest_id of this MoviesPurchasesBody.  # noqa: E501
        :rtype: str
        """
        return self._guest_id

    @guest_id.setter
    def guest_id(self, guest_id):
        """Sets the guest_id of this MoviesPurchasesBody.

        The guest ID  # noqa: E501

        :param guest_id: The guest_id of this MoviesPurchasesBody.  # noqa: E501
        :type: str
        """

        self._guest_id = guest_id

    @property
    def reservation_id(self):
        """Gets the reservation_id of this MoviesPurchasesBody.  # noqa: E501

        The reservation ID  # noqa: E501

        :return: The reservation_id of this MoviesPurchasesBody.  # noqa: E501
        :rtype: str
        """
        return self._reservation_id

    @reservation_id.setter
    def reservation_id(self, reservation_id):
        """Sets the reservation_id of this MoviesPurchasesBody.

        The reservation ID  # noqa: E501

        :param reservation_id: The reservation_id of this MoviesPurchasesBody.  # noqa: E501
        :type: str
        """

        self._reservation_id = reservation_id

    @property
    def room_id(self):
        """Gets the room_id of this MoviesPurchasesBody.  # noqa: E501

        The room ID  # noqa: E501

        :return: The room_id of this MoviesPurchasesBody.  # noqa: E501
        :rtype: str
        """
        return self._room_id

    @room_id.setter
    def room_id(self, room_id):
        """Sets the room_id of this MoviesPurchasesBody.

        The room ID  # noqa: E501

        :param room_id: The room_id of this MoviesPurchasesBody.  # noqa: E501
        :type: str
        """

        self._room_id = room_id

    @property
    def movie_id(self):
        """Gets the movie_id of this MoviesPurchasesBody.  # noqa: E501

        The ID of the movie to purhase  # noqa: E501

        :return: The movie_id of this MoviesPurchasesBody.  # noqa: E501
        :rtype: str
        """
        return self._movie_id

    @movie_id.setter
    def movie_id(self, movie_id):
        """Sets the movie_id of this MoviesPurchasesBody.

        The ID of the movie to purhase  # noqa: E501

        :param movie_id: The movie_id of this MoviesPurchasesBody.  # noqa: E501
        :type: str
        """
        if movie_id is None:
            raise ValueError("Invalid value for `movie_id`, must not be `None`")  # noqa: E501

        self._movie_id = movie_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MoviesPurchasesBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MoviesPurchasesBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
