# coding: utf-8

"""
    Nevaya Platform

    Access to everything Nevaya  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@nevaya.co.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ReceiverApplication(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'catch_up': 'bool',
        'translations': 'list[ReceiverApplicationTranslation]',
        'mirroring': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'catch_up': 'catch_up',
        'translations': 'translations',
        'mirroring': 'mirroring'
    }

    def __init__(self, id=None, catch_up=None, translations=None, mirroring=None):  # noqa: E501
        """ReceiverApplication - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._catch_up = None
        self._translations = None
        self._mirroring = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if catch_up is not None:
            self.catch_up = catch_up
        if translations is not None:
            self.translations = translations
        if mirroring is not None:
            self.mirroring = mirroring

    @property
    def id(self):
        """Gets the id of this ReceiverApplication.  # noqa: E501


        :return: The id of this ReceiverApplication.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ReceiverApplication.


        :param id: The id of this ReceiverApplication.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def catch_up(self):
        """Gets the catch_up of this ReceiverApplication.  # noqa: E501

        Is the application a catch up app, e.g. iPlayer, All 4 etc  # noqa: E501

        :return: The catch_up of this ReceiverApplication.  # noqa: E501
        :rtype: bool
        """
        return self._catch_up

    @catch_up.setter
    def catch_up(self, catch_up):
        """Sets the catch_up of this ReceiverApplication.

        Is the application a catch up app, e.g. iPlayer, All 4 etc  # noqa: E501

        :param catch_up: The catch_up of this ReceiverApplication.  # noqa: E501
        :type: bool
        """

        self._catch_up = catch_up

    @property
    def translations(self):
        """Gets the translations of this ReceiverApplication.  # noqa: E501

        Translations for the application  # noqa: E501

        :return: The translations of this ReceiverApplication.  # noqa: E501
        :rtype: list[ReceiverApplicationTranslation]
        """
        return self._translations

    @translations.setter
    def translations(self, translations):
        """Sets the translations of this ReceiverApplication.

        Translations for the application  # noqa: E501

        :param translations: The translations of this ReceiverApplication.  # noqa: E501
        :type: list[ReceiverApplicationTranslation]
        """

        self._translations = translations

    @property
    def mirroring(self):
        """Gets the mirroring of this ReceiverApplication.  # noqa: E501

        Is the application a mirroring app allowing the guest device to share their screen.  # noqa: E501

        :return: The mirroring of this ReceiverApplication.  # noqa: E501
        :rtype: bool
        """
        return self._mirroring

    @mirroring.setter
    def mirroring(self, mirroring):
        """Sets the mirroring of this ReceiverApplication.

        Is the application a mirroring app allowing the guest device to share their screen.  # noqa: E501

        :param mirroring: The mirroring of this ReceiverApplication.  # noqa: E501
        :type: bool
        """

        self._mirroring = mirroring

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ReceiverApplication, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReceiverApplication):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
