# coding: utf-8

"""
    Nevaya Platform

    Access to everything Nevaya  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@nevaya.co.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TvReceiversBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'site_id': 'str',
        'page': 'int',
        'per_page': 'int',
        'room_id': 'str',
        'room_name_eq': 'str',
        'room_name_cont': 'str',
        'receiver_ids': 'list[str]'
    }

    attribute_map = {
        'site_id': 'site_id',
        'page': 'page',
        'per_page': 'per_page',
        'room_id': 'room_id',
        'room_name_eq': 'room_name_eq',
        'room_name_cont': 'room_name_cont',
        'receiver_ids': 'receiver_ids'
    }

    def __init__(self, site_id=None, page=None, per_page=None, room_id=None, room_name_eq=None, room_name_cont=None, receiver_ids=None):  # noqa: E501
        """TvReceiversBody - a model defined in Swagger"""  # noqa: E501
        self._site_id = None
        self._page = None
        self._per_page = None
        self._room_id = None
        self._room_name_eq = None
        self._room_name_cont = None
        self._receiver_ids = None
        self.discriminator = None
        if site_id is not None:
            self.site_id = site_id
        if page is not None:
            self.page = page
        if per_page is not None:
            self.per_page = per_page
        if room_id is not None:
            self.room_id = room_id
        if room_name_eq is not None:
            self.room_name_eq = room_name_eq
        if room_name_cont is not None:
            self.room_name_cont = room_name_cont
        if receiver_ids is not None:
            self.receiver_ids = receiver_ids

    @property
    def site_id(self):
        """Gets the site_id of this TvReceiversBody.  # noqa: E501

        May be ignored depending on user access rights, for example if the user only has access to a single site that sites' ID will be used  # noqa: E501

        :return: The site_id of this TvReceiversBody.  # noqa: E501
        :rtype: str
        """
        return self._site_id

    @site_id.setter
    def site_id(self, site_id):
        """Sets the site_id of this TvReceiversBody.

        May be ignored depending on user access rights, for example if the user only has access to a single site that sites' ID will be used  # noqa: E501

        :param site_id: The site_id of this TvReceiversBody.  # noqa: E501
        :type: str
        """

        self._site_id = site_id

    @property
    def page(self):
        """Gets the page of this TvReceiversBody.  # noqa: E501

        Required page number in paginated results  # noqa: E501

        :return: The page of this TvReceiversBody.  # noqa: E501
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page):
        """Sets the page of this TvReceiversBody.

        Required page number in paginated results  # noqa: E501

        :param page: The page of this TvReceiversBody.  # noqa: E501
        :type: int
        """

        self._page = page

    @property
    def per_page(self):
        """Gets the per_page of this TvReceiversBody.  # noqa: E501

        Number of results per page  # noqa: E501

        :return: The per_page of this TvReceiversBody.  # noqa: E501
        :rtype: int
        """
        return self._per_page

    @per_page.setter
    def per_page(self, per_page):
        """Sets the per_page of this TvReceiversBody.

        Number of results per page  # noqa: E501

        :param per_page: The per_page of this TvReceiversBody.  # noqa: E501
        :type: int
        """

        self._per_page = per_page

    @property
    def room_id(self):
        """Gets the room_id of this TvReceiversBody.  # noqa: E501

        The room ID  # noqa: E501

        :return: The room_id of this TvReceiversBody.  # noqa: E501
        :rtype: str
        """
        return self._room_id

    @room_id.setter
    def room_id(self, room_id):
        """Sets the room_id of this TvReceiversBody.

        The room ID  # noqa: E501

        :param room_id: The room_id of this TvReceiversBody.  # noqa: E501
        :type: str
        """

        self._room_id = room_id

    @property
    def room_name_eq(self):
        """Gets the room_name_eq of this TvReceiversBody.  # noqa: E501

        The room name matches the value exactly  # noqa: E501

        :return: The room_name_eq of this TvReceiversBody.  # noqa: E501
        :rtype: str
        """
        return self._room_name_eq

    @room_name_eq.setter
    def room_name_eq(self, room_name_eq):
        """Sets the room_name_eq of this TvReceiversBody.

        The room name matches the value exactly  # noqa: E501

        :param room_name_eq: The room_name_eq of this TvReceiversBody.  # noqa: E501
        :type: str
        """

        self._room_name_eq = room_name_eq

    @property
    def room_name_cont(self):
        """Gets the room_name_cont of this TvReceiversBody.  # noqa: E501

        The room name contains the value  # noqa: E501

        :return: The room_name_cont of this TvReceiversBody.  # noqa: E501
        :rtype: str
        """
        return self._room_name_cont

    @room_name_cont.setter
    def room_name_cont(self, room_name_cont):
        """Sets the room_name_cont of this TvReceiversBody.

        The room name contains the value  # noqa: E501

        :param room_name_cont: The room_name_cont of this TvReceiversBody.  # noqa: E501
        :type: str
        """

        self._room_name_cont = room_name_cont

    @property
    def receiver_ids(self):
        """Gets the receiver_ids of this TvReceiversBody.  # noqa: E501

        Array of receiver IDs  # noqa: E501

        :return: The receiver_ids of this TvReceiversBody.  # noqa: E501
        :rtype: list[str]
        """
        return self._receiver_ids

    @receiver_ids.setter
    def receiver_ids(self, receiver_ids):
        """Sets the receiver_ids of this TvReceiversBody.

        Array of receiver IDs  # noqa: E501

        :param receiver_ids: The receiver_ids of this TvReceiversBody.  # noqa: E501
        :type: list[str]
        """

        self._receiver_ids = receiver_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TvReceiversBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TvReceiversBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
