# coding: utf-8

"""
    Nevaya Platform

    Access to everything Nevaya  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@nevaya.co.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WifiVouchersBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tariff_id': 'str',
        'count': 'int',
        'expires_in': 'int'
    }

    attribute_map = {
        'tariff_id': 'tariff_id',
        'count': 'count',
        'expires_in': 'expires_in'
    }

    def __init__(self, tariff_id=None, count=1, expires_in=1):  # noqa: E501
        """WifiVouchersBody - a model defined in Swagger"""  # noqa: E501
        self._tariff_id = None
        self._count = None
        self._expires_in = None
        self.discriminator = None
        self.tariff_id = tariff_id
        self.count = count
        if expires_in is not None:
            self.expires_in = expires_in

    @property
    def tariff_id(self):
        """Gets the tariff_id of this WifiVouchersBody.  # noqa: E501


        :return: The tariff_id of this WifiVouchersBody.  # noqa: E501
        :rtype: str
        """
        return self._tariff_id

    @tariff_id.setter
    def tariff_id(self, tariff_id):
        """Sets the tariff_id of this WifiVouchersBody.


        :param tariff_id: The tariff_id of this WifiVouchersBody.  # noqa: E501
        :type: str
        """
        if tariff_id is None:
            raise ValueError("Invalid value for `tariff_id`, must not be `None`")  # noqa: E501

        self._tariff_id = tariff_id

    @property
    def count(self):
        """Gets the count of this WifiVouchersBody.  # noqa: E501

        How many vouchers should be created  # noqa: E501

        :return: The count of this WifiVouchersBody.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this WifiVouchersBody.

        How many vouchers should be created  # noqa: E501

        :param count: The count of this WifiVouchersBody.  # noqa: E501
        :type: int
        """
        if count is None:
            raise ValueError("Invalid value for `count`, must not be `None`")  # noqa: E501

        self._count = count

    @property
    def expires_in(self):
        """Gets the expires_in of this WifiVouchersBody.  # noqa: E501

        How many days before the voucher expires  # noqa: E501

        :return: The expires_in of this WifiVouchersBody.  # noqa: E501
        :rtype: int
        """
        return self._expires_in

    @expires_in.setter
    def expires_in(self, expires_in):
        """Sets the expires_in of this WifiVouchersBody.

        How many days before the voucher expires  # noqa: E501

        :param expires_in: The expires_in of this WifiVouchersBody.  # noqa: E501
        :type: int
        """

        self._expires_in = expires_in

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WifiVouchersBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WifiVouchersBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
